### ISSUE TITLE
Cannot receive the email after registration

### ISSUE THREAD

**Issue by SamLukeYes** [makedeb/infrastucture#1]
I've tried registering with multiple email addresses (including Outlook, Gmail and others), but none of them received the password resetting email.

**Comment by hwittenborn** [comment]
I'm not really sure why this is happening. At current, I'm thinking one of the following is causing the issues:

1. My email provider (Zoho)
2. aurweb itself

The one I'm mostly like going to be able to rule out first is #2, and will require me to try to dig into the backend code for the MPR and see what might be causing the issue.

If I end up not being able to get anywhere with that, I'll try experimenting with other email providers and see if I get any better luck.

**Comment by SamLukeYes** [comment]
I've tried the email address that I used to register on AUR, but it doesn't work on MPR.

**Comment by hwittenborn** [comment]
The backend code that's used for the MPR currently differs from the AUR, so it's (theoretically) possible that an issue could be present (and a couple have already been found, such as with the generation of comments on package pages).

Not sure how likely it would be, but it's definitely a possibility a bug could still be present in the code for the MPR.

**Comment by hwittenborn** [comment]
See the above commit as to why the issue was happening.

The issue now has a workaround in the deployed release though that should work fine.
